### ISSUE TITLE
Notice: Undefined variable: escaper

### ISSUE THREAD

**Issue by reshadzazai** [mageprince/magento2-buynow#44]
Magento ver 2.3.6
1 exception(s):
Exception #0 (Exception): Notice: Undefined variable: escaper in /var/www/html/app/code/Mageprince/BuyNow/view/frontend/templates/buynow-view.phtml on line 18

**Comment by mageprince** [comment]
Hi @reshadzazai, thank you for your report.
This is due to backward compatibility. `$escaper` of class `\Magento\Framework\Escaper` only supported after Magento 2.4.
We reverted back to `$block` to support with 2.3.x. Please download the latest code.
Related commit: https://github.com/mageprince/magento2-buynow/commit/96e43a6307b2f8823928118a894131c81b915016
